name       : haskell-syb
version    : '0.7'
release    : 5
source     :
    - https://hackage.haskell.org/package/syb-0.7/syb-0.7.tar.gz : b8757dce5ab4045c49a0ae90407d575b87ee5523a7dd5dfa5c9d54fcceff42b5
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains the generics system described in the Scrap Your Boilerplate papers
description: |
    This package contains the generics system described in the Scrap Your Boilerplate papers
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
