name       : haskell-syb
version    : 0.7.1
release    : 7
source     :
    - https://hackage.haskell.org/package/syb-0.7.1/syb-0.7.1.tar.gz : e04a9c7ae48d9fe25e9b7a064f7122d39c710753544511e15df7a6e87fdfe700
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package contains the generics system described in the Scrap Your Boilerplate papers
description: |
    This package contains the generics system described in the Scrap Your Boilerplate papers
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
