name       : haskell-syb
version    : 0.6
release    : 1
source     :
    - http://hackage.haskell.org/package/syb-0.6/syb-0.6.tar.gz : a38d1f7e6a40e2c990fec85215c45063a508bf73df98a4483ec78c5025b66cdc
license    : BSD-3-Clause
component  : programming
summary    : This package contains the generics system described in the Scrap Your Boilerplate papers
description: |
    This package contains the generics system described in the Scrap Your Boilerplate papers
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 syb-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/syb-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/syb-$version/*.a
